FROM golang:1.9-alpine as kubetoken-builder

RUN apk add -U git make
RUN git clone https://github.com/invia-de/kubetoken /go/src/github.com/invia-de/kubetoken && \
    cd /go/src/github.com/invia-de/kubetoken && \
    make deps build-kubetoken build-kubetokend
